services:
   prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports: 
       - 9090:9090
      volumes:
       - prom-data:/prometheus
       - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      command:
       - '--config.file=/etc/prometheus/prometheus.yml'
       - '--storage.tsdb.retention.time=14d'
      restart: unless-stopped
   grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
       - 3000:3000
      volumes:
       - grafana-data:/var/lib/grafana
      restart: unless-stopped

volumes:
   prom-data:
   grafana-data: 
