services:
   prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports: 
       - 9090:9090
      volumes:
       - prom-data:/prometheus
       - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      command:
       - '--config.file=/etc/prometheus/prometheus.yml'
       - '--storage.tsdb.retention.time=14d'
      restart: unless-stopped
   grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
       - 3000:3000
      volumes:
       - grafana-data:/var/lib/grafana
      environment:
         - GF_SECURITY_ADMIN_USER=admin
         - GF_SECURITY_ADMIN_PASSWORD=malik
      restart: unless-stopped
   node-exporter:
      image: prom/node-exporter
      container_name: node-exporter
      ports:
       - 9100:9100
      restart: unless-stopped
   blackbox-exporter:
      image: prom/blackbox-exporter
      container_name: blackbox-exporter
      ports:
       - 9115:9115
      volumes:
       - './blackbox.yml:/config/blackbox.yml'
      command:
        '--config.file=/config/blackbox.yml'
      restart: unless-stopped

volumes:
   prom-data:
   grafana-data: 
